### ISSUE TITLE
Fix bug on canceling an upc tutoring session (Student)

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#130]
### Steps to recreate this bug
1. Log in as a student.
2. Click on an upcoming tutoring session and cancel the session.
3. Navigate to the Booking view using the bottom nav bar. This should crash the application.

```
FATAL EXCEPTION: main
                                                            Process: cs.dal.krush, PID: 3546
                                                            android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
                                                                at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                                at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
                                                                at cs.dal.krush.studentFragments.StudentUpcSessionsDetailsFragment.onCreateView(StudentUpcSessionsDetailsFragment.java:84)
                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2353)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

There's an issue with the cursor trying to access index 0 with a size of 0. This needs to be investigated and fixed.

Further testing must be done on Tutor Upcoming Sessions.

**Comment by Mons1Oerjan** [comment]
Done!

**Comment by Mons1Oerjan** [comment]
This task is done with Mike's PR
