### ISSUE TITLE
Fix bug on booking a tutor with the student booking view

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#131]
### Recreating this bug
1. Log in as a student.
2. Navigate to the Booking view.
3. Click on a tutor in the list and click on the "Book Now" button. This should crash the application.

```
FATAL EXCEPTION: main
                                                            Process: cs.dal.krush, PID: 6292
                                                            android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
                                                                at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
                                                                at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                                at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
                                                                at cs.dal.krush.studentFragments.StudentTutorDetailsFragment.onClick(StudentTutorDetailsFragment.java:173)
                                                                at android.view.View.performClick(View.java:5637)
                                                                at android.view.View$PerformClick.run(View.java:22429)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

This needs to be investigated and fixed.

**Comment by Mons1Oerjan** [comment]
done!
