### ISSUE TITLE
Fix bug on timeslot deletion on Tutor Availability view

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#132]
### Recreating this bug
1. Log in as a tutor.
2. Go to the Availability view.
3. Add a new available timeslot (I chose today's date and 3-4pm).
4. Click the submit button and then click on the newly created availability item in the list view.
5. Click on the trash can / delete button. The application crashes.

```
FATAL EXCEPTION: main
                                                            Process: cs.dal.krush, PID: 8002
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cs.dal.krush.helpers.DateFormatHelper.formatForSqlite(java.lang.String, java.lang.String)' on a null object reference
                                                                at cs.dal.krush.adapters.CustomTutorDayTimeAdapter$1.onClick(CustomTutorDayTimeAdapter.java:101)
                                                                at android.view.View.performClick(View.java:5637)
                                                                at android.view.View$PerformClick.run(View.java:22429)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

This must be investigated and fixed.

EDIT: Deleting an already existing timeslot also crashes the application with the same error message.

**Comment by gregpmillr** [comment]
See PR #136
