### ISSUE TITLE
Fix error messages on Tutor Session History view

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#133]
### Recreating the error message
1. Log in as a tutor.
2. Go to the session History view
3. Click on a list item. This throws the following error in the logcat:

```
E/SQLiteCursor: requesting column name with table name -- t.f_name
                                                            java.lang.Exception
                                                                at android.database.sqlite.SQLiteCursor.getColumnIndex(SQLiteCursor.java:179)
                                                                at cs.dal.krush.tutorFragments.TutorHistoryDetailsFragment.onCreateView(TutorHistoryDetailsFragment.java:75)
                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-28 00:55:52.342 15068-15068/cs.dal.krush E/SQLiteCursor: requesting column name with table name -- t.l_name
                                                            java.lang.Exception
                                                                at android.database.sqlite.SQLiteCursor.getColumnIndex(SQLiteCursor.java:179)
                                                                at cs.dal.krush.tutorFragments.TutorHistoryDetailsFragment.onCreateView(TutorHistoryDetailsFragment.java:76)
                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-28 00:55:52.342 15068-15068/cs.dal.krush E/SQLiteCursor: requesting column name with table name -- t.email
                                                            java.lang.Exception
                                                                at android.database.sqlite.SQLiteCursor.getColumnIndex(SQLiteCursor.java:179)
                                                                at cs.dal.krush.tutorFragments.TutorHistoryDetailsFragment.onCreateView(TutorHistoryDetailsFragment.java:77)
                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

(I used the "meeting on Starbucks on Robie St with Greg Miller" session to get this bug).

This must be fixed.

**Comment by Mons1Oerjan** [comment]
See PR #137
